# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 02:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('doctype', models.TextField()),
                ('docnum', models.TextField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sign', models.TextField()),
                ('signtitle', models.TextField()),
                ('images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('raw_body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
