# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170911_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Document')),
                ('mnchn_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('adolescent_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('spec_pop_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('geriatric_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
