# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='adolescent_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='label',
            name='geriatric_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='label',
            name='mnchn_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='label',
            name='spec_pop_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
